### ISSUE TITLE
Integrate Help Widgets Module

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/help-widgets-module#2]
Integrate Help Widgets Module into CSIS and provide help texts **(?)** and examples **(i)** .

![grafik](https://user-images.githubusercontent.com/1788226/50207199-14b1e700-036e-11e9-9093-57c3aed0c3aa.png)

**Comment by patrickkaleta** [comment]
As it was mentioned in [this comment](https://github.com/clarity-h2020/docker-drupal/issues/13#issuecomment-421906151) the "Help Widgets" module has been configured for the "Textarea" and "Textfield" fieldtypes and also works in the context of Groups now. I also created the contextual help pages (without any actual content!) and linked them to the corresponding fields in the forms.  

**Next steps** would be to determine for which other fieldtypes will need this help widgets and who can fill the contextual help pages with actual and informative data + real examples (maybe @DanielRodera or someone from the Science team?).

Since this is not a pressing issue right now, i suppose this can wait until after the next review.

**Comment by p-a-s-c-a-l** [comment]
IMHO adding the help messages and examples is something that could be easily done by @DanielRodera with support from @patrickkaleta. WDYT?

![grafik](https://user-images.githubusercontent.com/1788226/59614195-8b168280-9120-11e9-92af-a4f6ea89531c.png)

See also https://github.com/clarity-h2020/docker-drupal/issues/13#issuecomment-433821515

**Comment by patrickkaleta** [comment]
> IMHO adding the help messages and examples is something that could be easily done by @DanielRodera with support from @patrickkaleta. WDYT?
> 

Should be possible. The Study forms changed quite a bit since [that issue](https://github.com/clarity-h2020/docker-drupal/issues/13) was last discussed. I'll first have a look at which additional fields could need those help icons and then discuss further proceeding with @DanielRodera

**Comment by DanielRodera** [comment]
> Should be possible. The Study forms changed quite a bit since that issue was last discussed. I'll first have a look at which additional fields could need those help icons and then discuss further proceeding with @DanielRodera

How is this task going? if you need anything please let me know!

**Comment by patrickkaleta** [comment]
> > Should be possible. The Study forms changed quite a bit since that issue was last discussed. I'll first have a look at which additional fields could need those help icons and then discuss further proceeding with @DanielRodera
> 
> How is this task going? if you need anything please let me know!

I wanted to get to it, but now the changes to the data package model proposed by Miguel got in the way. @DanielRodera I will contact you with detailed instruction on how to add the help pages later today or over the weekend.

**Comment by p-a-s-c-a-l** [comment]
Will this module work out of the box with the [new theme](https://github.com/clarity-h2020/clarity-theme/issues/1) or is is independent of that?

**Comment by patrickkaleta** [comment]
It should work out of the box. It has a a little bit of css included, which might need to be adapted a little for the new theme, but the functionality should not be effected by a new theme.

**Comment by DanielRodera** [comment]
I have added the help text for the study with @patrickkaleta´s support. We also disscused about that and we decided to keep only one help text per field with a short description and an example. 

Please let me know if you need to add another help texts.
